USE [NSDC_Skills]
GO

/****** Object:  Table [dbo].[NSDC_SMART_TP_DETAIL]    Script Date: 8/21/2018 4:50:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NSDC_SDMS_TP_DETAIL](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[TP_Name] [nvarchar](200) NULL,
	[TP_SDMS_ID] BIGINT NULL,
	[TP_SMART_ID] [nvarchar](100) NULL,
	[TP_SPOC_Name] [nvarchar](100) NULL,
	[TP_SPOC_Mobile_No] [nvarchar](50) NULL,
	[TP_SPOC_Email_Id] [nvarchar](100) NULL,
	
 CONSTRAINT [PK_NSDC_SDMS_3214EC0787E67969] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


