
--12 record
insert into NSDC_SDMS_TP_DETAIL (TP_Name,TP_SDMS_ID,TP_SMART_ID,TP_SPOC_Name,TP_SPOC_Mobile_No,TP_SPOC_Email_Id,IS_Threshold)
select distinct A.tp,'' tp_sdms, A.smarttpid,  tpspoc,  tpspocmobile,  tpspocemail, 0 from  (

select '' sdmsid,'TC060289' smartcentreid,'MADHYANCHAL UTKARSH BAHUUDDESHIYA VIKAS SAMITI' tp,'Litchitree Skills_ similiguda(27)_odisha' tc, 'ODISHA' statename, 'KORAPUT' district ,'No' ispmkk ,'TP000645' smarttpid, 'AJAY KUMAR SINGH' tpspoc, '9755663354' tpspocmobile, 'madhyanchal.2013@gmail.com' tpspocemail, 'Sanjay' tcspoc ,'7008730034' tcspocmobile ,'madhyanchal.similiguda@gmail.com' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC061976' smartcentreid,'JOIN2 OUR FOUNDATION' tp,'JOIN2 OUR FOUNDATION KANDHAMAL' tc, 'ODISHA' statename, 'KANDHAMAL' district ,'No' ispmkk ,'TP015534' smarttpid, 'Santosh Kumar Pattanayak' tpspoc, '9213436173' tpspocmobile, 'join2ourfoundation@gmail.com' tpspocemail, 'ADITYA KUMAR PATRA' tcspoc ,'9439589992' tcspocmobile ,'jeetpatra029@gmail.com' tcspocemail, '90' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC062473' smartcentreid,'Kaushal Shala Foundation' tp,'Mount Litera Zee School' tc, 'PUNJAB' statename, 'LUDHIANA' district ,'No' ispmkk ,'TP015516' smarttpid, 'Deepinder Kaur' tpspoc, '8968628869' tpspocmobile, 'info@kaushalshala.org' tpspocemail, 'Ankush Sharma' tcspoc ,'9988227551' tcspocmobile ,'ankushoa@gmail.com' tcspocemail, '30' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC063611' smartcentreid,'ANAAYAS FOUNDATION' tp,'anaayas foundation' tc, 'UTTAR PRADESH' statename, 'MATHURA' district ,'No' ispmkk ,'TP011501' smarttpid, 'Akshat Kulshrestha' tpspoc, '8273555048' tpspocmobile, 'anaayasfoundation@gmail.com' tpspocemail, 'Abhinav Gupta' tcspoc ,'8279959679' tcspocmobile ,'abhinavguptamtr@hotmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC063656' smartcentreid,'ANAAYAS FOUNDATION' tp,'anaayas foundation' tc, 'UTTAR PRADESH' statename, 'HATHRAS' district ,'No' ispmkk ,'TP011501' smarttpid, 'Akshat Kulshrestha' tpspoc, '8273555048' tpspocmobile, 'anaayasfoundation@gmail.com' tpspocemail, 'Hariom Agrawal' tcspoc ,'8445412368' tcspocmobile ,'anaayasfoundation01@gmail.com' tcspocemail, '210' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC101442' smartcentreid,'ANAAYAS FOUNDATION' tp,'ANAAYAS FOUNDATION FOROZABAD' tc, 'UTTAR PRADESH' statename, 'FIROZABAD' district ,'No' ispmkk ,'TP011501' smarttpid, 'Akshat Kulshrestha' tpspoc, '8273555048' tpspocmobile, 'anaayasfoundation@gmail.com' tpspocemail, 'Dr. Rajni Yadav' tcspoc ,'8279811910' tcspocmobile ,'anaayasfoundations2@gmail.com' tcspocemail, '180' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC105319' smartcentreid,'JOIN2 OUR FOUNDATION' tp,'JOIN2 OUR FOUNDATION CUDDALORE' tc, 'TAMIL NADU' statename, 'CUDDALORE' district ,'No' ispmkk ,'TP015534' smarttpid, 'Santosh Kumar Pattanayak' tpspoc, '9213436173' tpspocmobile, 'join2ourfoundation@gmail.com' tpspocemail, 'loganathan k' tcspoc ,'8056346208' tcspocmobile ,'sawarigo@gmail.com' tcspocemail, '90' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC109349' smartcentreid,'National Institute of Electronics & Information Technology (NIELIT)' tp,'NIELIT KOLKATA JU CAMPUS' tc, 'WEST BENGAL' statename, 'KOLKATA' district ,'No' ispmkk ,'TP002580' smarttpid, 'Sharmistha Bhattacharjee' tpspoc, '9073304894' tpspocmobile, 'sharmi9870@yahoo.com' tpspocemail, 'Sharmistha Bhattacharjee' tcspoc ,'9073304894' tcspocmobile ,'sharmi9870@yahoo.com' tcspocemail, '40' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC109608' smartcentreid,'Vendor Plus Consultants Private Limited' tp,'Vendor Plus Consultants Private Limited' tc, 'ODISHA' statename, 'NUAPADA' district ,'No' ispmkk ,'TP001666' smarttpid, 'Ms Priyanka Nandwani' tpspoc, '7428159875' tpspocmobile, 'priyanka.nandwani1@gmail.com' tpspocemail, 'Ravindar singh' tcspoc ,'9315303840' tcspocmobile ,'ravindar.vendorplus@yahoo.com' tcspocemail, '330' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC110116' smartcentreid,'J&K Youth Development Forum' tp,'J&K Youth Development Forum' tc, 'JAMMU AND KASHMIR' statename, 'BADGAM' district ,'No' ispmkk ,'TP009825' smarttpid, 'SHEHRE YAR MAJEED' tpspoc, '9906460333' tpspocmobile, 'shehreyardar00@gmail.com' tpspocemail, 'TARIQ AHMAD' tcspoc ,'7889899694' tcspocmobile ,'jkydfchadoora@gmail.com' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC110914' smartcentreid,'MS AMINA NAZAR TRADING' tp,'MS AMINA NAZAR TRADING - KARGIL' tc, 'JAMMU AND KASHMIR' statename, 'KARGIL' district ,'No' ispmkk ,'TP004869' smarttpid, 'SHAHID ALAM' tpspoc, '9934806515' tpspocmobile, 'anskill03@gmail.com' tpspocemail, 'OWN ALI' tcspoc ,'8651074297' tcspocmobile ,'eregimine2015@gmail.com' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC111629' smartcentreid,'AISECT SKILLS MISSION' tp,'AISECT PMKK Kanpur Dehat' tc, 'UTTAR PRADESH' statename, 'KANPUR DEHAT' district ,'Yes' ispmkk ,'TP000717' smarttpid, 'Sanjeev Gupta' tpspoc, '9827338853' tpspocmobile, 'sanjeevgupta@aisect.org' tpspocemail, 'Aman Singh' tcspoc ,'9044027291' tcspocmobile ,'pmkkkanpurdehat.ch@aisect.org' tcspocemail, '235' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC111797' smartcentreid,'JEYRAM EDUCATIONAL TRUST' tp,'JEYRAM EDUCATIONAL TRUST' tc, 'TAMIL NADU' statename, 'THANJAVUR' district ,'Yes' ispmkk ,'TP000329' smarttpid, 'M. Sambat' tpspoc, '9750962827' tpspocmobile, 'jedutrust@gmail.com' tpspocemail, 'P  VENKATESH' tcspoc ,'9750962830' tcspocmobile ,'jet.thanjavur.pmkk@gmail.com' tcspocemail, '390' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC113331' smartcentreid,'JITM SKILLS Pvt Ltd' tp,'PMKK JITM Kasaragod' tc, 'KERALA' statename, 'KASARAGOD' district ,'Yes' ispmkk ,'TP000302' smarttpid, 'Prof Yogesh Kumar' tpspoc, '9891676453' tpspocmobile, 'jitmskillspvtltd@gmail.com' tpspocemail, 'Sanjeev' tcspoc ,'9999348777' tcspocmobile ,'kasaragod.pmkk@gmail.com' tcspocemail, '30' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC115304' smartcentreid,'Centum WorkSkills India Limited' tp,'PMKK Baramati' tc, 'MAHARASHTRA' statename, 'PUNE' district ,'Yes' ispmkk ,'TP000072' smarttpid, 'Mehwash Siddiqui' tpspoc, '9821118026' tpspocmobile, 'mehwash.siddiqui@centumlearning.com' tpspocemail, 'Milind B Bhole' tcspoc ,'9922832386' tcspocmobile ,'pmkk.baramaticnln@gmail.com' tcspocemail, '180' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC115323' smartcentreid,'Foresight Edutech Private Limited' tp,'F-TEC MBPL PMKK Barmer' tc, 'RAJASTHAN' statename, 'BARMER' district ,'Yes' ispmkk ,'TP000078' smarttpid, 'Shalu Bhatia' tpspoc, '9811354636' tpspocmobile, 'ed@f-tec.net.in' tpspocemail, 'Divya Prakash' tcspoc ,'8209701861' tcspocmobile ,'pmkkbarmer@f-tec.net.in' tcspocemail, '77' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC116490' smartcentreid,'Scope Learning Resources Pvt Ltd' tp,'Scope Skill' tc, 'ODISHA' statename, 'JAJAPUR' district ,'No' ispmkk ,'TP002235' smarttpid, 'sanjeeva vyas' tpspoc, '9754428585' tpspocmobile, 'Vyasimpact@gmail.com' tpspocemail, 'SUBRAT KUMAR ROUT' tcspoc ,'7077033521' tcspocmobile ,'scope.newjajpur@gmail.com' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC116498' smartcentreid,'STAR SECUTECH PRIVATE LIMITED' tp,'Star PMKK- Chandauli' tc, 'UTTAR PRADESH' statename, 'CHANDAULI' district ,'Yes' ispmkk ,'TP001224' smarttpid, 'Jayant Kumar Harlalka' tpspoc, '9540780999' tpspocmobile, 'starsecutech@gmail.com' tpspocemail, 'Jayant Harlalka' tcspoc ,'9911038832' tcspocmobile ,'cm.pmkk.chandauli@starsecutech.com' tcspocemail, '300' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC116600' smartcentreid,'RAJEEV GANDHI COMPUTER PRASAR MISSION SANSTHAN' tp,'RGCPM SKILL ACADEMY  MANDRELLA' tc, 'RAJASTHAN' statename, 'JHUNJHUNU' district ,'No' ispmkk ,'TP002942' smarttpid, 'IMRAN KHAN' tpspoc, '9829237799' tpspocmobile, 'mdrgcpm@gmail.com' tpspocemail, 'JULEKHA BANO' tcspoc ,'8769275050' tcspocmobile ,'rgcpmrfpmandrella@gmail.com' tcspocemail, '180' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117192' smartcentreid,'G K EDUCATIONAL TRUST' tp,'GKITR-Reasi' tc, 'JAMMU AND KASHMIR' statename, 'REASI' district ,'Yes' ispmkk ,'TP000686' smarttpid, 'gourav khajuria' tpspoc, '9469211425' tpspocmobile, 'gouravkhajuriassn@gmail.com' tpspocemail, 'Ankita Gaur' tcspoc ,'9796221204' tcspocmobile ,'pmkkreasi@gmail.com' tcspocemail, '360' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117325' smartcentreid,'TDS PLACEMENTS AND SERVICES PRIVATE LIMITED' tp,'TDS PLACEMENTS AND SERVICES PVT LTD HISAR' tc, 'HARYANA' statename, 'HISAR' district ,'No' ispmkk ,'TP050735' smarttpid, 'RAKESH CHANDRA BALONNI' tpspoc, '8219160633' tpspocmobile, 'project.csr3@gmail.com' tpspocemail, 'rinku' tcspoc ,'9466114600' tcspocmobile ,'spochisar@gmail.com' tcspocemail, '360' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117764' smartcentreid,'TDS PLACEMENTS AND SERVICES PRIVATE LIMITED' tp,'TDS PLACEMENTS AND SERVICES PVT LTD EAST CHAMPARAN' tc, 'BIHAR' statename, 'PURBI CHAMPARAN' district ,'No' ispmkk ,'TP050735' smarttpid, 'RAKESH CHANDRA BALONNI' tpspoc, '8219160633' tpspocmobile, 'project.csr3@gmail.com' tpspocemail, 'VICKY RAJ' tcspoc ,'7079074677' tcspocmobile ,'tdsplacementbihar@gmail.com' tcspocemail, '360' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117864' smartcentreid,'TDS PLACEMENTS AND SERVICES PRIVATE LIMITED' tp,'TDS PLACEMENTS AND SERVICES PVT LTD SAGAR' tc, 'MADHYA PRADESH' statename, 'SAGAR' district ,'No' ispmkk ,'TP050735' smarttpid, 'RAKESH CHANDRA BALONNI' tpspoc, '8219160633' tpspocmobile, 'project.csr3@gmail.com' tpspocemail, 'PRADEEP KUMAR JAIN' tcspoc ,'9826267998' tcspocmobile ,'tdsplacementsagar@gmail.com' tcspocemail, '323' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117871' smartcentreid,'TDS PLACEMENTS AND SERVICES PRIVATE LIMITED' tp,'TDS PLACEMENTS AND SERVICES PVT LTD PATIALA' tc, 'PUNJAB' statename, 'PATIALA' district ,'No' ispmkk ,'TP050735' smarttpid, 'RAKESH CHANDRA BALONNI' tpspoc, '8219160633' tpspocmobile, 'project.csr3@gmail.com' tpspocemail, 'OMBIR' tcspoc ,'9416378499' tcspocmobile ,'SPOCPATIALA@GMAIL.COM' tcspocemail, '360' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117905' smartcentreid,'Mosaic Network (India) Private Limited' tp,'PMKK-Mosaic  Shivpuri' tc, 'MADHYA PRADESH' statename, 'SHIVPURI' district ,'Yes' ispmkk ,'TP001380' smarttpid, 'Siddharth Gopawat' tpspoc, '9098978247' tpspocmobile, 'utkarsh.shrivastava@mosaicworkskills.com' tpspocemail, 'Abhijeet Agarwal' tcspoc ,'7566901004' tcspocmobile ,'shivpuri@4qlearning.com' tcspocemail, '660' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117926' smartcentreid,'TDS PLACEMENTS AND SERVICES PRIVATE LIMITED' tp,'TDS PLACEMENTS AND SERVICES PVT LTD KHUNTI' tc, 'JHARKHAND' statename, 'KHUNTI' district ,'No' ispmkk ,'TP050735' smarttpid, 'RAKESH CHANDRA BALONNI' tpspoc, '8219160633' tpspocmobile, 'project.csr3@gmail.com' tpspocemail, 'SWEKSHA SHUKLA' tcspoc ,'9546615795' tcspocmobile ,'tdsplacementkhunti@gmail.com' tcspocemail, '175' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC117927' smartcentreid,'TDS PLACEMENTS AND SERVICES PRIVATE LIMITED' tp,'TDS PLACEMENTS AND SERVICES PVT LTD GARHWA' tc, 'JHARKHAND' statename, 'GARHWA' district ,'No' ispmkk ,'TP050735' smarttpid, 'RAKESH CHANDRA BALONNI' tpspoc, '8219160633' tpspocmobile, 'project.csr3@gmail.com' tpspocemail, 'SWEKCHA SHUKLA' tcspoc ,'9006324326' tcspocmobile ,'TDSPLACEMENTGARHWA@GMAIL.COM' tcspocemail, '360' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC118060' smartcentreid,'DIVINE' tp,'DIVINE INSTITUTE OF ENGINEERING AND TECHNOLOGY' tc, 'ODISHA' statename, 'MAYURBHANJ' district ,'No' ispmkk ,'TP016237' smarttpid, 'ABHINNA KUMAR DAS' tpspoc, '7008261824' tpspocmobile, 'DIETBARIPADA@GMAIL.COM' tpspocemail, 'ABHINNA KUMAR DAS' tcspoc ,'7008261824' tcspocmobile ,'skill.divine09@gmail.com' tcspocemail, '248' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC118101' smartcentreid,'Ultimate Energy Resource Private Limited' tp,'PMKVY Bhopal Centre' tc, 'MADHYA PRADESH' statename, 'BHOPAL' district ,'No' ispmkk ,'TP000312' smarttpid, 'Sahil Wali' tpspoc, '6264902261' tpspocmobile, 'sahil@ecocapita.in' tpspocemail, 'jatin singh' tcspoc ,'6262029904' tcspocmobile ,'pmkvybhopalcentre@ecocapita.in' tcspocemail, '90' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC118460' smartcentreid,'Foresight Edutech Private Limited' tp,'FEPL Palam' tc, 'DELHI' statename, 'SOUTH WEST' district ,'No' ispmkk ,'TP000078' smarttpid, 'Shalu Bhatia' tpspoc, '9811354636' tpspocmobile, 'ed@f-tec.net.in' tpspocemail, 'Gourav Singh' tcspoc ,'8851797980' tcspocmobile ,'fepl.palam@gmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC118647' smartcentreid,'Better Place Safety Solutions Pvt. Ltd.' tp,'Better Place Safety Solution Pvt. Ltd.' tc, 'HARYANA' statename, 'BHIWANI' district ,'No' ispmkk ,'TP055677' smarttpid, 'Abhishek Grover' tpspoc, '8130377888' tpspocmobile, 'abhishek.grover@betterplace.co.in' tpspocemail, 'Sanjay Singh' tcspoc ,'9992938850' tcspocmobile ,'rmshk121@gmail.com' tcspocemail, '130' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC118688' smartcentreid,'NATIONAL PARAMEDICAL SCIENCES SOCIETY' tp,'PMKK-Kishtwar' tc, 'JAMMU AND KASHMIR' statename, 'KISHTWAR' district ,'Yes' ispmkk ,'TP000679' smarttpid, 'JAI KUMAR' tpspoc, '7404322226' tpspocmobile, 'SKILLYNR@GMAIL.COM' tpspocemail, 'Vineet Bhutyal' tcspoc ,'9906216634' tcspocmobile ,'npsspmkk@gmail.com' tcspocemail, '500' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC118914' smartcentreid,'NISHA PUBLIC WELFARE AND EDUCATIONAL TRUST' tp,'NATIONAL TRAINING CENTRE AZAMGARH' tc, 'UTTAR PRADESH' statename, 'AZAMGARH' district ,'No' ispmkk ,'TP055268' smarttpid, 'FIROZ AHMAD KHAN' tpspoc, '9919583113' tpspocmobile, '786sultanahmadkhan@gmail.com' tpspocemail, 'VINEET KUMAR SHARMA' tcspoc ,'8423172829' tcspocmobile ,'azamgarh.national@gmail.com' tcspocemail, '217' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC119107' smartcentreid,'Skills Art and Beyond Social Welfare Society' tp,'SAB VTC Kaimur' tc, 'BIHAR' statename, 'KAIMUR (BHABUA)' district ,'No' ispmkk ,'TP004810' smarttpid, 'Karan Girdhar' tpspoc, '7999539819' tpspocmobile, 'karan@sabsociety.org' tpspocemail, 'Chandeshver Prasad' tcspoc ,'9340406211' tcspocmobile ,'sabvtckaimur@gmail.com' tcspocemail, '60' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC119110' smartcentreid,'Skills Art and Beyond Social Welfare Society' tp,'SAB VTC Ganderbal' tc, 'JAMMU AND KASHMIR' statename, 'GANDERBAL' district ,'No' ispmkk ,'TP004810' smarttpid, 'Karan Girdhar' tpspoc, '7999539819' tpspocmobile, 'karan@sabsociety.org' tpspocemail, 'Azad Ahmad Rather' tcspoc ,'7006287700' tcspocmobile ,'sabvtcganderbal@gmail.com' tcspocemail, '30' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC119176' smartcentreid,'DATAPRO COMPUTERS PRIVATE LIMITED' tp,'Datapro Nuapada' tc, 'ODISHA' statename, 'NUAPADA' district ,'Yes' ispmkk ,'TP000440' smarttpid, 'KSB. KISHORE VARMA' tpspoc, '9573377755' tpspocmobile, 'kishore@datapro.in' tpspocemail, 'Sangram' tcspoc ,'7436877746' tcspocmobile ,'pmkknuapada.datapro@gmail.com' tcspocemail, '411' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC119222' smartcentreid,'Ultimate Energy Resource Private Limited' tp,'Hyderabad PMKVY' tc, 'TELANGANA' statename, 'HYDERABAD' district ,'No' ispmkk ,'TP000312' smarttpid, 'Sahil Wali' tpspoc, '6264902261' tpspocmobile, 'sahil@ecocapita.in' tpspocemail, 'A. Reshma' tcspoc ,'9505965621' tcspocmobile ,'Hyderabadpmkvy@ecocapita.in' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC119224' smartcentreid,'Ultimate Energy Resource Private Limited' tp,'Nagarkurnool PMKVY CENTRE' tc, 'TELANGANA' statename, 'NAGARKURNOOL' district ,'No' ispmkk ,'TP000312' smarttpid, 'Sahil Wali' tpspoc, '6264902261' tpspocmobile, 'sahil@ecocapita.in' tpspocemail, 'M . Ramakanth' tcspoc ,'9441016450' tcspocmobile ,'Nagarkurnoolpmkvy@ecocapita.in' tcspocemail, '169' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC119226' smartcentreid,'Ultimate Energy Resource Private Limited' tp,'Visakhapatnam PMKVY Centre' tc, 'ANDHRA PRADESH' statename, 'VISAKHAPATANAM' district ,'No' ispmkk ,'TP000312' smarttpid, 'Sahil Wali' tpspoc, '6264902261' tpspocmobile, 'sahil@ecocapita.in' tpspocemail, 'J. Hanuman Naik' tcspoc ,'7661026905' tcspocmobile ,'pmkvy@ecocapita.in' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120100' smartcentreid,'Orion Edutech Pvt Ltd' tp,'PMKK Hooghly' tc, 'WEST BENGAL' statename, 'HOOGHLY' district ,'Yes' ispmkk ,'TP001497' smarttpid, 'Somnath Acharya' tpspoc, '9830409181' tpspocmobile, 'somnathacharya@orionedutech.com' tpspocemail, 'Sandipan Ghosh' tcspoc ,'8420420097' tcspocmobile ,'hoogly.pmkk@orionedutech.in' tcspocemail, '858' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120196' smartcentreid,'DYNAMIC ENTERPRISES' tp,'WORLD WORKERS PVT ITI' tc, 'MADHYA PRADESH' statename, 'DHAR' district ,'No' ispmkk ,'TP055026' smarttpid, 'PRAKASH MALPANI' tpspoc, '9644000652' tpspocmobile, 'INFOTECH_ASSOCIATES_RTM@YAHOO.CO.IN' tpspocemail, 'GAURAV JAIN' tcspoc ,'8359903033' tcspocmobile ,'world.workers.iti@gmail.com' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120271' smartcentreid,'Foresight Edutech Private Limited' tp,'FEPL Khajuri' tc, 'DELHI' statename, 'NORTH EAST' district ,'No' ispmkk ,'TP000078' smarttpid, 'Shalu Bhatia' tpspoc, '9811354636' tpspocmobile, 'ed@f-tec.net.in' tpspocemail, 'keshar bano' tcspoc ,'9910323292' tcspocmobile ,'fepl.khajuri@gmail.com' tcspocemail, '176' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120625' smartcentreid,'Directorate of Indian Army Veterans DIAV' tp,'ASTC BEG ROORKEE' tc, 'UTTARAKHAND' statename, 'HARIDWAR' district ,'No' ispmkk ,'TP008775' smarttpid, 'Vikas Bhardwaj' tpspoc, '9418848827' tpspocmobile, 'armyskilling@gmail.com' tpspocemail, 'SANDEEP BENIWAL' tcspoc ,'9450188633' tcspocmobile ,'ciwbegr@gmail.com' tcspocemail, '60' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120644' smartcentreid,'DYNAMIC ENTERPRISES' tp,'NARSINGPUR SKILL CENTER' tc, 'MADHYA PRADESH' statename, 'NARSINGHPUR' district ,'No' ispmkk ,'TP055026' smarttpid, 'PRAKASH MALPANI' tpspoc, '9644000652' tpspocmobile, 'INFOTECH_ASSOCIATES_RTM@YAHOO.CO.IN' tpspocemail, 'OMPRAKASH LODHI' tcspoc ,'7987625457' tcspocmobile ,'kori.deepak27@gmail.com' tcspocemail, '329' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120695' smartcentreid,'M/s Pioneer Embroideries Ltd' tp,'M/s Pioneer Embroideries Ltd' tc, 'HIMACHAL PRADESH' statename, 'SIRMAUR' district ,'No' ispmkk ,'TP057422' smarttpid, 'Sonia Chadha' tpspoc, '9855420256' tpspocmobile, 'sonia.march2222@gmail.com' tpspocemail, 'Dr. Sonia Chadha' tcspoc ,'9855420256' tcspocmobile ,'sonia.march@gmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC120885' smartcentreid,'CARE EDUCATIONAL AND WELFARE SOCIETY' tp,'PMKK-Baramulla' tc, 'JAMMU AND KASHMIR' statename, 'BARAMULLA' district ,'Yes' ispmkk ,'TP001220' smarttpid, 'MS. SHILPA' tpspoc, '8800697061' tpspocmobile, 'project.mgr@cews.in' tpspocemail, 'Mudassir Abdullah' tcspoc ,'9906404791' tcspocmobile ,'baramulla@cews.in' tcspocemail, '720' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC121297' smartcentreid,'Directorate of Indian Army Veterans DIAV' tp,'ASTC NAGROTA' tc, 'JAMMU AND KASHMIR' statename, 'JAMMU' district ,'No' ispmkk ,'TP008775' smarttpid, 'Vikas Bhardwaj' tpspoc, '9418848827' tpspocmobile, 'armyskilling@gmail.com' tpspocemail, 'UDHISHTEER KHALDANIA' tcspoc ,'9414038487' tcspocmobile ,'astcnagrota16@gmail.com' tcspocemail, '54' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC121415' smartcentreid,'Skills Art and Beyond Social Welfare Society' tp,'SAB VTC Pulwama' tc, 'JAMMU AND KASHMIR' statename, 'PULWAMA' district ,'No' ispmkk ,'TP004810' smarttpid, 'Karan Girdhar' tpspoc, '7999539819' tpspocmobile, 'karan@sabsociety.org' tpspocemail, 'Mudasir Ahmed Tali' tcspoc ,'6005473315' tcspocmobile ,'sabvtcpulwama@gmail.com' tcspocemail, '60' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC121443' smartcentreid,'Skills Art and Beyond Social Welfare Society' tp,'SAB VTC Satna' tc, 'MADHYA PRADESH' statename, 'SATNA' district ,'No' ispmkk ,'TP004810' smarttpid, 'Karan Girdhar' tpspoc, '7999539819' tpspocmobile, 'karan@sabsociety.org' tpspocemail, 'Deepak Kumar Kori' tcspoc ,'9713763682' tcspocmobile ,'sabvtcsatna@gmail.com' tcspocemail, '60' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC121446' smartcentreid,'Skills Art and Beyond Social Welfare Society' tp,'SAB VTC Shajapur' tc, 'MADHYA PRADESH' statename, 'SHAJAPUR' district ,'No' ispmkk ,'TP004810' smarttpid, 'Karan Girdhar' tpspoc, '7999539819' tpspocmobile, 'karan@sabsociety.org' tpspocemail, 'Pratap Singh Sisodia' tcspoc ,'9993067969' tcspocmobile ,'sabvtcshajapur@gmail.com' tcspocemail, '90' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC121785' smartcentreid,'Amass Skill Ventures Pvt. Ltd.' tp,'Amass Skill Ventures-Auraiya' tc, 'UTTAR PRADESH' statename, 'AURAIYA' district ,'No' ispmkk ,'TP002514' smarttpid, 'Deepa Suyal' tpspoc, '7840010603' tpspocmobile, 'finance@amassskillventures.in' tpspocemail, 'Ram Ji' tcspoc ,'8077074041' tcspocmobile ,'auraiyaamass@gmail.com' tcspocemail, '90' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC121916' smartcentreid,'Shiva HR Solutions Pvt Ltd' tp,'Shiva HR Solutions Pvt Ltd' tc, 'UTTAR PRADESH' statename, 'GHAZIABAD' district ,'No' ispmkk ,'TP055124' smarttpid, 'Ashok Tyagi' tpspoc, '9643559718' tpspocmobile, 'ashoktyagilkgi@gmail.com' tpspocemail, 'Ashok Tyagi' tcspoc ,'9310650311' tcspocmobile ,'ashoktyagilkgi@gmail.com' tcspocemail, '308' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC122073' smartcentreid,'kanchan india limited' tp,'Kanchan India Skills School Bhilwara' tc, 'RAJASTHAN' statename, 'BHILWARA' district ,'No' ispmkk ,'TP006571' smarttpid, 'Rakesh Kumar Sharma' tpspoc, '7357710714' tpspocmobile, 'kanchanskillsspoc@gmail.com' tpspocemail, 'Rakesh Kumar Sharma' tcspoc ,'9782810714' tcspocmobile ,'kanchanskillsspoc@gmail.com' tcspocemail, '290' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC122122' smartcentreid,'DYNAMIC ENTERPRISES' tp,'S K FASHION AND DESIGN INSTITUTE' tc, 'MADHYA PRADESH' statename, 'RATLAM' district ,'No' ispmkk ,'TP055026' smarttpid, 'PRAKASH MALPANI' tpspoc, '9644000652' tpspocmobile, 'INFOTECH_ASSOCIATES_RTM@YAHOO.CO.IN' tpspocemail, 'SAURABH KATARIYA' tcspoc ,'9424476073' tcspocmobile ,'saurabh20katariya@gmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC122286' smartcentreid,'GARG ACRYLICS LTD' tp,'GARG ACRYLICS LTD' tc, 'PUNJAB' statename, 'LUDHIANA' district ,'No' ispmkk ,'TP056144' smarttpid, 'RAKESH KUMAR' tpspoc, '9855003487' tpspocmobile, 'gargacrylics.pmkvy@gmail.com' tpspocemail, 'RAKESH KUMAR' tcspoc ,'9855003487' tcspocmobile ,'RAKESHKK1976@GMAIL.COM' tcspocemail, '52' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC122704' smartcentreid,'Vardhman Textiles Limited' tp,'VTXL Centre 2' tc, 'HIMACHAL PRADESH' statename, 'SOLAN' district ,'No' ispmkk ,'TP005670' smarttpid, 'Mr. gaurav kapoor' tpspoc, '8146625352' tpspocmobile, 'gauravkapoor@vardhman.com' tpspocemail, 'Mohan Jangra' tcspoc ,'8894723205' tcspocmobile ,'mohanjangra@vardhman.com' tcspocemail, '49' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC122876' smartcentreid,'DEEPAK SPINNERS LIMITED' tp,'Deepak Spinners Ltd' tc, 'MADHYA PRADESH' statename, 'GUNA' district ,'No' ispmkk ,'TP057013' smarttpid, 'Hitendra Kumar Tiwari' tpspoc, '7018905553' tpspocmobile, 'hktiwari@dslindia.in' tpspocemail, 'Sanjay Tripathi' tcspoc ,'8349994602' tcspocmobile ,'stripathi@dslindia.in' tcspocemail, '150' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123174' smartcentreid,'Ultimate Energy Resource Private Limited' tp,'Ultimate skills centre mandideep' tc, 'MADHYA PRADESH' statename, 'RAISEN' district ,'No' ispmkk ,'TP000312' smarttpid, 'Sahil Wali' tpspoc, '6264902261' tpspocmobile, 'sahil@ecocapita.in' tpspocemail, 'Pawan Singh' tcspoc ,'8109678546' tcspocmobile ,'mandideeppmkvy@ecocapita.in' tcspocemail, '120' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123213' smartcentreid,'Asian Gates Welfare Society' tp,'Asian Gates Welfare Society' tc, 'UTTAR PRADESH' statename, 'MUZAFFARNAGAR' district ,'No' ispmkk ,'TP058021' smarttpid, 'Priyanka' tpspoc, '8595140857' tpspocmobile, 'agws.skills@gmail.com' tpspocemail, 'JAG MOHAN CHANDHOK' tcspoc ,'6399917008' tcspocmobile ,'agws.muzaffarnagar@gmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123225' smartcentreid,'Asian Gates Welfare Society' tp,'Asian Gates Welfare Society' tc, 'UTTAR PRADESH' statename, 'MUZAFFARNAGAR' district ,'No' ispmkk ,'TP058021' smarttpid, 'Priyanka' tpspoc, '8595140857' tpspocmobile, 'agws.skills@gmail.com' tpspocemail, 'Prachi Rathi' tcspoc ,'7300652724' tcspocmobile ,'gatesasian@gmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123241' smartcentreid,'Asian Gates Welfare Society' tp,'Asian Gates Welfare Society' tc, 'UTTAR PRADESH' statename, 'MUZAFFARNAGAR' district ,'No' ispmkk ,'TP058021' smarttpid, 'Priyanka' tpspoc, '8595140857' tpspocmobile, 'agws.skills@gmail.com' tpspocemail, 'Ashvin Kumar' tcspoc ,'7300652724' tcspocmobile ,'pmkvyasian@gmail.com' tcspocemail, '240' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123311' smartcentreid,'IND SWIFT LIMITED' tp,'Swift Training Academy' tc, 'PUNJAB' statename, 'PATIALA' district ,'No' ispmkk ,'TP055038' smarttpid, 'Sonia Chadha' tpspoc, '9646125578' tpspocmobile, 'march_sonia@yahoo.co.in' tpspocemail, 'Dr. Sonia Chadha' tcspoc ,'7837036038' tcspocmobile ,'march.sonia@gmail.com' tcspocemail, '192' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123355' smartcentreid,'Foresight Edutech Private Limited' tp,'FEPL Bhalaswa' tc, 'DELHI' statename, 'NORTH WEST' district ,'No' ispmkk ,'TP000078' smarttpid, 'Shalu Bhatia' tpspoc, '9811354636' tpspocmobile, 'ed@f-tec.net.in' tpspocemail, 'Swapnil singh' tcspoc ,'9811535363' tcspocmobile ,'fepl.bhalaswa@gmail.com' tcspocemail, '60' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC123375' smartcentreid,'Foresight Edutech Private Limited' tp,'FEPL Haridwar' tc, 'UTTARAKHAND' statename, 'HARIDWAR' district ,'No' ispmkk ,'TP000078' smarttpid, 'Shalu Bhatia' tpspoc, '9811354636' tpspocmobile, 'ed@f-tec.net.in' tpspocemail, 'Ankush Walia' tcspoc ,'9718500866' tcspocmobile ,'fepl.haridwar@gmail.com' tcspocemail, '220' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC124227' smartcentreid,'DEEPAK SPINNERS LIMITED' tp,'Deepak Spinners Limited' tc, 'HIMACHAL PRADESH' statename, 'SOLAN' district ,'No' ispmkk ,'TP057013' smarttpid, 'Hitendra Kumar Tiwari' tpspoc, '7018905553' tpspocmobile, 'hktiwari@dslindia.in' tpspocemail, 'Chetan Sharma' tcspoc ,'7069133133' tcspocmobile ,'baddi@dsl-india.com' tcspocemail, '180' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC124434' smartcentreid,'Asian Gates Welfare Society' tp,'Asian Gates Welfare Society' tc, 'UTTAR PRADESH' statename, 'SAHARANPUR' district ,'No' ispmkk ,'TP058021' smarttpid, 'Priyanka' tpspoc, '8595140857' tpspocmobile, 'agws.skills@gmail.com' tpspocemail, 'Mohd Kashif Jamal' tcspoc ,'9756198072' tcspocmobile ,'pmkvyasian@gmail.com' tcspocemail, '360' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC124527' smartcentreid,'kanchan india limited' tp,'Kanchan india skill school nimbahera' tc, 'RAJASTHAN' statename, 'CHITTORGARH' district ,'No' ispmkk ,'TP006571' smarttpid, 'Rakesh Kumar Sharma' tpspoc, '7357710714' tpspocmobile, 'kanchanskillsspoc@gmail.com' tpspocemail, 'Jitendra Singh' tcspoc ,'8769707364' tcspocmobile ,'kanchan.pmkvynimbahera@gmail.com' tcspocemail, '206' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC125227' smartcentreid,'Amass Skill Ventures Pvt. Ltd.' tp,'Amass Skill Ventures Rewari' tc, 'HARYANA' statename, 'REWARI' district ,'No' ispmkk ,'TP002514' smarttpid, 'Deepa Suyal' tpspoc, '7840010603' tpspocmobile, 'finance@amassskillventures.in' tpspocemail, 'Jaswant Singh' tcspoc ,'9466023590' tcspocmobile ,'rewariamass@gmail.com' tcspocemail, '30' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
 union all select '' sdmsid,'TC125602' smartcentreid,'Magnum Super Distributors India Private Limited' tp,'MSD SKILLS' tc, 'MADHYA PRADESH' statename, 'BHOPAL' district ,'No' ispmkk ,'TP002122' smarttpid, 'Sachin Saxena' tpspoc, '9926560435' tpspocmobile, 'tpspoc.pmkvy@gmail.com' tpspocemail, 'Sohail Ahmed khan' tcspoc ,'9755009829' tcspocmobile ,'tcspocpmkvy@gmail.com' tcspocemail, '363' enrolled, '0' trained , '0' assesed, '0' certified, '0' placed
)A where not exists (select 1 from NSDC_SDMS_TP_DETAIL where TP_SMART_ID = a.smarttpid)