--select * from districtwise_jobrole 
update districtwise_jobrole  set isactive=0
where id not in (
select id from districtwise_jobrole a
inner join (
select 'AMH/Q1947' jobcode     
union all select 'BWS/Q0202' jobcode     
union all select 'ELE/Q3104' jobcode     
union all select 'HSS/Q5101' jobcode     
union all select 'ELE/Q4605' jobcode     
union all select 'CON/Q0602' jobcode     
union all select 'DWC/Q0102' jobcode     
union all select 'FIC/Q0102' jobcode     
union all select 'SGJ/Q0201' jobcode     
union all select 'SSC/Q2702' jobcode     
union all select 'TSC/Q7303' jobcode     
union all select 'AMH/Q0301' jobcode     
union all select 'BWS/Q0102' jobcode     
union all select 'ELE/Q4601' jobcode     
union all select 'ELE/Q5901' jobcode     
union all select 'LSC/Q1122' jobcode     
union all select 'MES/Q0601' jobcode     
union all select 'HSS/Q5501' jobcode     
union all select 'CSC/Q0402' jobcode     
union all select 'ELE/Q9302' jobcode     
union all select 'FIC/Q9007' jobcode     
union all select 'AMH/Q1001' jobcode     
union all select 'THC/Q0102' jobcode     
union all select 'SGJ/Q0101' jobcode     
union all select 'PSS/Q0107' jobcode     
union all select 'ASC/Q1411' jobcode     
union all select 'CON/Q0605' jobcode     
union all select 'HSS/Q2701' jobcode     
union all select 'AMH/Q1210' jobcode     
union all select 'AMH/Q1910' jobcode     
union all select 'CON/Q0103' jobcode     
union all select 'SSC/Q0110' jobcode     
union all select 'PSC/Q0104' jobcode     
union all select 'HCS/Q5701' jobcode     
union all select 'HCS/Q6601' jobcode     
union all select 'LFS/Q0401' jobcode     
union all select 'TEL/Q0100' jobcode     
union all select 'AMH/Q0305' jobcode     
union all select 'RAS/Q0101' jobcode     
union all select 'THC/Q4402' jobcode     
union all select 'BSC/Q0910' jobcode     
union all select 'BSC/Q8101' jobcode     
union all select 'BWS/Q0301' jobcode     
union all select 'PSC/Q0102' jobcode     
union all select 'TEL/Q0102' jobcode     
union all select 'TEL/Q6400' jobcode     
union all select 'HCS/Q7301' jobcode     
union all select 'SGJ/Q0107' jobcode     
union all select 'ASC/Q1103' jobcode     
union all select 'HCS/Q5301' jobcode     
union all select 'TEL/Q2201' jobcode     
union all select 'HSS/Q5501' jobcode     
union all select 'THC/Q0208' jobcode     
union all select 'AMH/Q0901' jobcode     
union all select 'LSC/Q3023' jobcode     
union all select 'RAS/Q0604' jobcode     
union all select 'SSC/Q2211' jobcode     
union all select 'THC/Q0301' jobcode     
union all select 'BWS/Q0101' jobcode     
union all select 'HSS/Q5401' jobcode     
union all select 'PSS/Q6001' jobcode     
union all select 'MEP/Q0202' jobcode     
union all select 'HSS/Q8601' jobcode     
union all select 'CON/Q0102' jobcode     
union all select 'HSS/Q2301' jobcode     
union all select 'MES/Q1801' jobcode     
union all select 'DWC/Q0201' jobcode     
union all select 'PSS/Q3001' jobcode     
union all select 'AGR/Q4908' jobcode     
union all select 'SPF/Q1102' jobcode     
union all select 'LSC/Q0101' jobcode     
union all select 'LSC/Q1120' jobcode     
union all select 'ASC/Q1401' jobcode     
union all select 'ASC/Q1401' jobcode     
union all select 'BSC/Q8401' jobcode     
union all select 'THC/Q3006' jobcode     
union all select 'AMH/Q1801' jobcode     
union all select 'MEP/Q7104' jobcode     
union all select 'MES/Q0702' jobcode     
union all select 'MES/Q0706' jobcode     
union all select 'ASC/Q1103' jobcode     
union all select 'ASC/Q1902' jobcode     
union all select 'BWS/Q0201' jobcode     
union all select 'ELE/Q3102' jobcode     
union all select 'HCS/Q5412' jobcode     
union all select 'RAS/Q0102' jobcode     
union all select 'THC/Q2903' jobcode     
union all select 'THC/Q4404' jobcode     
union all select 'ELE/Q8101' jobcode     
union all select 'AMH/Q1901' jobcode     
union all select 'THC/Q0109' jobcode     
union all select 'SSC/Q2213' jobcode     
union all select 'SGJ/Q8702' jobcode     
union all select 'DWC/Q0101' jobcode     
union all select 'LSC/Q2303' jobcode     
union all select 'ELE/Q4606' jobcode     
union all select 'THC/Q0406' jobcode     
union all select 'FIC/Q0103' jobcode     
union all select 'HSS/Q5103' jobcode     
union all select 'RAS/Q0106' jobcode     
union all select 'FIC/Q2002' jobcode     
union all select 'FIC/Q7002' jobcode     
union all select 'AMH/Q1010' jobcode     
union all select 'FIC/Q0106' jobcode     
union all select 'HSS/Q5102' jobcode     
union all select 'HSS/Q8703' jobcode     
union all select 'TEL/Q0200' jobcode     
union all select 'FIC/Q5005' jobcode     
union all select 'FIC/Q7004' jobcode     
union all select 'HSS/Q2401' jobcode     
union all select 'TSC/Q4101' jobcode     
union all select 'ELE/Q7201' jobcode     
union all select 'THC/Q4501' jobcode     
union all select 'FIC/Q0101' jobcode     
union all select 'FIC/Q5002' jobcode     
union all select 'AMH/Q0610' jobcode     
)t on a.tradecode=t.jobcode
where a.isactive=1
)
and isactive=1
